import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
	index("routes/home.tsx"),
	route("quran", "routes/quran/index.tsx"),
	route("quran/:number", "routes/quran/surah.tsx"),
	route("quran/:number/:ayah", "routes/quran/ayah.tsx"),
	route("quran/juz/:number", "routes/quran/juz.tsx"),
	route("hadith", "routes/hadith/index.tsx"),
	route("hadith/:book", "routes/hadith/book.tsx"),
	route("hadith/:book/:number", "routes/hadith/hadith.tsx"),
	route("prayer-times", "routes/prayer-times.tsx"),
	route("search", "routes/search.tsx"),
	route("asmaul-husna", "routes/asmaul-husna.tsx"),
	route("prayer", "routes/prayer.tsx"),
	route("more", "routes/more.tsx"),
	route("settings", "routes/settings.tsx"),
	route("murajaah", "routes/murajaah.tsx"),
	route("murajaah/tracker", "routes/murajaah/tracker.tsx"),
	route("login", "routes/login.tsx"),
	route("register", "routes/register.tsx"),
	route("user-profile", "routes/user-profile.tsx"),
	route("odoj", "routes/odoj.tsx"),
	route("odoj/create", "routes/odoj-create.tsx"),
	route("odoj/history", "routes/odoj-history.tsx"),
	route("odoj/history/:date", "routes/odoj-history-date.tsx"),
	route("odoj/view", "routes/odoj-view.tsx"),
	route("sitemap.xml", "routes/sitemap.tsx"),
] satisfies RouteConfig;
